import { Router } from "express";

import { getProductos, getProductoByID, createProducto } from "../controllers/productosControllers.js";

const router = Router();
router.get('/productos', getProductos);
router.get('/productos/:id', getProductoByID);
router.post('/productos', createProducto);

export default router;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          